services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/test
      - SECRET=32876qihsdh76@&#!742(*#HG&#28702y&##@^!()(&^#))jhscbd
      - ACCESS_TOKEN_EXPIRY=1d
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-seed:/docker-entrypoint-initdb.d
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
